---
swagger: "2.0"
info:
  description: "Sample version of DSF-SE API for communication with the professional\
    \ UI"
  version: "0.0.2"
  title: "DSF-SE API"
  contact:
    email: "sisay.adugna.chala@fit.fraunhofer.de"
host: "simplon.fit.fraunhofer.de"
basePath: "/se"
tags:
- name: "grid"
  description: "Grid topology"
- name: "commands"
  description: "Commands for the simulation engine"
schemes:
- "http"
paths:
  /grid:
    post:
      tags:
      - "grid"
      summary: "Insert grid components"
      operationId: "create_grid"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        description: "Created grid. gridID = 0 because it is generated server-side"
        required: true
        schema:
          $ref: "#/definitions/Grid"
      responses:
        default:
          description: "successful operation"
      x-swagger-router-controller: "swagger_server.controllers.grid_controller"
  /grid/{id}:
    get:
      tags:
      - "grid"
      summary: "Get a grid topology"
      description: "Get a grid topology by the coordinates of its entry point transformer"
      operationId: "get_grid"
      produces:
      - "application/json"
      parameters:
      - name: "id"
        in: "path"
        description: "Id of the grid"
        required: true
        type: "integer"
        format: "int64"
      - in: "body"
        name: "coordinates"
        description: "The latitude and longitude coordinates for this grids entry\
          \ point"
        required: false
        schema:
          $ref: "#/definitions/Coordinates"
      responses:
        200:
          description: "successful operation"
          schema:
            $ref: "#/definitions/Grid"
        400:
          description: "Invalid parameters supplied"
        404:
          description: "Grid not found"
      x-swagger-router-controller: "swagger_server.controllers.grid_controller"
    put:
      tags:
      - "grid"
      summary: "Updated storage"
      description: ""
      operationId: "update_storage"
      produces:
      - "application/json"
      parameters:
      - name: "id"
        in: "path"
        description: "Id of the grid"
        required: true
        type: "integer"
        format: "int64"
      - in: "body"
        name: "body"
        description: "Updated grid components"
        required: true
        schema:
          $ref: "#/definitions/Grid"
      responses:
        400:
          description: "Invalid storage object supplied"
      x-swagger-router-controller: "swagger_server.controllers.grid_controller"
    delete:
      tags:
      - "grid"
      summary: "Delete storage"
      description: ""
      operationId: "delete_storage"
      produces:
      - "application/json"
      parameters:
      - name: "id"
        in: "path"
        description: "Id of the grid"
        required: true
        type: "integer"
        format: "int64"
      - in: "body"
        name: "body"
        description: "Deleted grid components"
        required: true
        schema:
          $ref: "#/definitions/Grid"
      responses:
        400:
          description: "Invalid ID supplied"
        404:
          description: "Storage not found"
      x-swagger-router-controller: "swagger_server.controllers.grid_controller"
  /commands/run:
    post:
      tags:
      - "commands"
      summary: "Runs a simulation"
      description: ""
      operationId: "run_simulation"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        description: "Run a simulation"
        required: true
        schema:
          $ref: "#/definitions/Simulation"
      responses:
        200:
          description: "successful operation"
          schema:
            type: "array"
            items:
              $ref: "#/definitions/SimulationResult"
        400:
          description: "Invalid user supplied"
        404:
          description: "User not found"
      x-swagger-router-controller: "swagger_server.controllers.commands_controller"
definitions:
  Grid:
    type: "object"
    properties:
      gridId:
        type: "integer"
      coordinates:
        $ref: "#/definitions/Coordinates"
      transformer:
        $ref: "#/definitions/Transformer"
      powerLines:
        type: "array"
        items:
          $ref: "#/definitions/Powerline"
      photovoltaics:
        type: "array"
        items:
          $ref: "#/definitions/Photovoltaic"
      storageUnits:
        type: "array"
        items:
          $ref: "#/definitions/Storage"
      chargingPoints:
        type: "array"
        items:
          $ref: "#/definitions/ChargingPoint"
    example:
      coordinates:
        latitude: 6
        longitude: 1
      transformer:
        voltagePrimary: 7.061401241503109105224211816675961017608642578125
        tapLevel: 4.9652184929849543237878606305457651615142822265625
        voltageSecondary: 9.301444243932575517419536481611430644989013671875
        Xeq: 1.489415909854170383397331534069962799549102783203125
        unitpower: "unitpower"
        latitude: 5
        monitor: 7
        control: 1
        voltageBaseSecondary: 2.027123023002321833274663731572218239307403564453125
        nodeLV: "nodeLV"
        voltageunit: "voltageunit"
        frequency: 5
        nodeHV: "nodeHV"
        voltageBasePrimary: 3.61607674925191080461672754609026014804840087890625
        noLoadLoss: 1.231513536777255612975068288506008684635162353515625
        connection: "connection"
        id: 5
        powerPrimary: 4
        powerSecondary: 7
        CeqTotal: 6.8468526983526398765889098285697400569915771484375
        longitude: 2
        Req: 1.024645700144157789424070870154537260532379150390625
      storageUnits:
      - inverterEfficiency: 0.10263654006109401706225980888120830059051513671875
        SoC: 7.14353804701230643559028976596891880035400390625
        powerunit: "powerunit"
        SoH: 7.05877035158235610623478351044468581676483154296875
        voltageunit: "voltageunit"
        voltage: 8.9695787981969115065794539987109601497650146484375
        node:
          latitude: 6
          id: 9
          longitude: 8
        powerfactor: 3.02057969929162428712743349024094641208648681640625
        DoD: 0.885137473901165261480628032586537301540374755859375
        id: 3
        power: 7.7403518187411730622216055053286254405975341796875
        phases: 4
        energy: 6.51918095101838179772357761976309120655059814453125
      - inverterEfficiency: 0.10263654006109401706225980888120830059051513671875
        SoC: 7.14353804701230643559028976596891880035400390625
        powerunit: "powerunit"
        SoH: 7.05877035158235610623478351044468581676483154296875
        voltageunit: "voltageunit"
        voltage: 8.9695787981969115065794539987109601497650146484375
        node:
          latitude: 6
          id: 9
          longitude: 8
        powerfactor: 3.02057969929162428712743349024094641208648681640625
        DoD: 0.885137473901165261480628032586537301540374755859375
        id: 3
        power: 7.7403518187411730622216055053286254405975341796875
        phases: 4
        energy: 6.51918095101838179772357761976309120655059814453125
      gridId: 0
      powerLines:
      - linecode: "linecode"
        node2:
          latitude: 6
          id: 9
          longitude: 8
        CeqTot: 3.557195227068097320710649000830017030239105224609375
        Xeq: 6.438423552598546706349225132726132869720458984375
        length: 1.2846590061165319429647979632136411964893341064453125
        id: 9
        node1:
          latitude: 6
          id: 9
          longitude: 8
        phases: 6
        unitlength: "unitlength"
        Req: 9.0183481860707832566959041287191212177276611328125
      - linecode: "linecode"
        node2:
          latitude: 6
          id: 9
          longitude: 8
        CeqTot: 3.557195227068097320710649000830017030239105224609375
        Xeq: 6.438423552598546706349225132726132869720458984375
        length: 1.2846590061165319429647979632136411964893341064453125
        id: 9
        node1:
          latitude: 6
          id: 9
          longitude: 8
        phases: 6
        unitlength: "unitlength"
        Req: 9.0183481860707832566959041287191212177276611328125
      chargingPoints:
      - node:
          latitude: 6
          id: 9
          longitude: 8
        id: 3
      - node:
          latitude: 6
          id: 9
          longitude: 8
        id: 3
      photovoltaics:
      - node:
          latitude: 6
          id: 9
          longitude: 8
        inverterEfficiency: 6.77832496304801335185175048536621034145355224609375
        powerfactor: 3.35319334701124294184637619764544069766998291015625
        powerunit: "powerunit"
        id: 2
        power: 6.70401929795003592715829654480330646038055419921875
        voltageunit: "voltageunit"
        phases: 6
        voltage: 5.94489560761401580890606055618263781070709228515625
      - node:
          latitude: 6
          id: 9
          longitude: 8
        inverterEfficiency: 6.77832496304801335185175048536621034145355224609375
        powerfactor: 3.35319334701124294184637619764544069766998291015625
        powerunit: "powerunit"
        id: 2
        power: 6.70401929795003592715829654480330646038055419921875
        voltageunit: "voltageunit"
        phases: 6
        voltage: 5.94489560761401580890606055618263781070709228515625
    xml:
      name: "Grid"
  Node:
    type: "object"
    properties:
      id:
        type: "integer"
      latitude:
        type: "integer"
      longitude:
        type: "integer"
    example:
      latitude: 6
      id: 9
      longitude: 8
  Coordinates:
    type: "object"
    properties:
      latitude:
        type: "integer"
      longitude:
        type: "integer"
    example:
      latitude: 6
      longitude: 1
  Powerline:
    type: "object"
    required:
    - "id"
    - "length"
    - "node1"
    - "node2"
    - "unitlength"
    properties:
      id:
        type: "integer"
        format: "int64"
      node1:
        $ref: "#/definitions/Node"
      node2:
        $ref: "#/definitions/Node"
      Req:
        type: "number"
      Xeq:
        type: "number"
      CeqTot:
        type: "number"
      phases:
        type: "integer"
        format: "int32"
      length:
        type: "number"
      unitlength:
        type: "string"
      linecode:
        type: "string"
    example:
      linecode: "linecode"
      node2:
        latitude: 6
        id: 9
        longitude: 8
      CeqTot: 3.557195227068097320710649000830017030239105224609375
      Xeq: 6.438423552598546706349225132726132869720458984375
      length: 1.2846590061165319429647979632136411964893341064453125
      id: 9
      node1:
        latitude: 6
        id: 9
        longitude: 8
      phases: 6
      unitlength: "unitlength"
      Req: 9.0183481860707832566959041287191212177276611328125
    xml:
      name: "Powerline"
  Storage:
    type: "object"
    required:
    - "DoD"
    - "SoC"
    - "id"
    - "node"
    properties:
      id:
        type: "integer"
      node:
        $ref: "#/definitions/Node"
      SoC:
        type: "number"
      DoD:
        type: "number"
      SoH:
        type: "number"
      energy:
        type: "number"
      inverterEfficiency:
        type: "number"
      phases:
        type: "integer"
      voltage:
        type: "number"
      voltageunit:
        type: "string"
      power:
        type: "number"
      powerunit:
        type: "string"
      powerfactor:
        type: "number"
    example:
      inverterEfficiency: 0.10263654006109401706225980888120830059051513671875
      SoC: 7.14353804701230643559028976596891880035400390625
      powerunit: "powerunit"
      SoH: 7.05877035158235610623478351044468581676483154296875
      voltageunit: "voltageunit"
      voltage: 8.9695787981969115065794539987109601497650146484375
      node:
        latitude: 6
        id: 9
        longitude: 8
      powerfactor: 3.02057969929162428712743349024094641208648681640625
      DoD: 0.885137473901165261480628032586537301540374755859375
      id: 3
      power: 7.7403518187411730622216055053286254405975341796875
      phases: 4
      energy: 6.51918095101838179772357761976309120655059814453125
  Photovoltaic:
    type: "object"
    required:
    - "id"
    - "node"
    - "power"
    properties:
      id:
        type: "integer"
      node:
        $ref: "#/definitions/Node"
      inverterEfficiency:
        type: "number"
      phases:
        type: "integer"
      voltage:
        type: "number"
      voltageunit:
        type: "string"
      power:
        type: "number"
      powerunit:
        type: "string"
      powerfactor:
        type: "number"
    example:
      node:
        latitude: 6
        id: 9
        longitude: 8
      inverterEfficiency: 6.77832496304801335185175048536621034145355224609375
      powerfactor: 3.35319334701124294184637619764544069766998291015625
      powerunit: "powerunit"
      id: 2
      power: 6.70401929795003592715829654480330646038055419921875
      voltageunit: "voltageunit"
      phases: 6
      voltage: 5.94489560761401580890606055618263781070709228515625
  ChargingPoint:
    type: "object"
    required:
    - "id"
    - "node"
    properties:
      id:
        type: "integer"
      node:
        $ref: "#/definitions/Node"
    example:
      node:
        latitude: 6
        id: 9
        longitude: 8
      id: 3
  Transformer:
    type: "object"
    required:
    - "id"
    properties:
      id:
        type: "integer"
      latitude:
        type: "integer"
      longitude:
        type: "integer"
      voltagePrimary:
        type: "number"
      voltageSecondary:
        type: "number"
      voltageBasePrimary:
        type: "number"
      voltageBaseSecondary:
        type: "number"
      powerPrimary:
        type: "integer"
      powerSecondary:
        type: "integer"
      connection:
        type: "string"
      nodeHV:
        type: "string"
      nodeLV:
        type: "string"
      noLoadLoss:
        type: "number"
      Req:
        type: "number"
      Xeq:
        type: "number"
      CeqTotal:
        type: "number"
      monitor:
        type: "integer"
      control:
        type: "integer"
      tapLevel:
        type: "number"
      voltageunit:
        type: "string"
      frequency:
        type: "integer"
      unitpower:
        type: "string"
    example:
      voltagePrimary: 7.061401241503109105224211816675961017608642578125
      tapLevel: 4.9652184929849543237878606305457651615142822265625
      voltageSecondary: 9.301444243932575517419536481611430644989013671875
      Xeq: 1.489415909854170383397331534069962799549102783203125
      unitpower: "unitpower"
      latitude: 5
      monitor: 7
      control: 1
      voltageBaseSecondary: 2.027123023002321833274663731572218239307403564453125
      nodeLV: "nodeLV"
      voltageunit: "voltageunit"
      frequency: 5
      nodeHV: "nodeHV"
      voltageBasePrimary: 3.61607674925191080461672754609026014804840087890625
      noLoadLoss: 1.231513536777255612975068288506008684635162353515625
      connection: "connection"
      id: 5
      powerPrimary: 4
      powerSecondary: 7
      CeqTotal: 6.8468526983526398765889098285697400569915771484375
      longitude: 2
      Req: 1.024645700144157789424070870154537260532379150390625
  Duration:
    type: "object"
    properties:
      day:
        type: "integer"
        format: "int32"
      month:
        type: "integer"
        format: "int32"
      year:
        type: "integer"
        format: "int32"
    example:
      month: 1
      year: 5
      day: 6
  Simulation:
    type: "object"
    properties:
      gridId:
        type: "integer"
        format: "int64"
      duration:
        $ref: "#/definitions/Duration"
      thresholdLow:
        type: "number"
        format: "float"
        description: "Lower threshold in % for voltage error"
      thresholdMedium:
        type: "number"
        format: "float"
        description: "Medium threshold in % for voltage error"
      thresholdHigh:
        type: "number"
        format: "float"
        description: "Maximum threshold in % for voltage error"
    example:
      duration:
        month: 1
        year: 5
        day: 6
      thresholdMedium: 2.302136
      gridId: 0
      thresholdHigh: 7.0614014
      thresholdLow: 5.637377
  SimulationResult:
    type: "object"
    required:
    - "nodeId"
    - "voltage"
    properties:
      nodeId:
        type: "integer"
        format: "int64"
      voltage:
        $ref: "#/definitions/Voltage"
      error:
        $ref: "#/definitions/Error"
    example:
      error:
        voltageT: true
        voltageR: true
        voltageS: true
      nodeId: 0
      voltage:
        voltageT: 5
        voltageR: 6
        voltageS: 1
  Voltage:
    type: "object"
    properties:
      voltageR:
        type: "integer"
        format: "int64"
      voltageS:
        type: "integer"
        format: "int64"
      voltageT:
        type: "integer"
        format: "int64"
    example:
      voltageT: 5
      voltageR: 6
      voltageS: 1
  Error:
    type: "object"
    properties:
      voltageR:
        type: "boolean"
      voltageS:
        type: "boolean"
      voltageT:
        type: "boolean"
    example:
      voltageT: true
      voltageR: true
      voltageS: true
externalDocs:
  description: "Find out more about Swagger"
  url: "http://swagger.io"
